"""schema_refinement_final

Revision ID: 32c51f0bfb26
Revises: 
Create Date: 2026-01-31 16:12:50.301841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32c51f0bfb26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'version', name='uq_lens_key_ver')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('batch_index', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REJECTED', 'ARCHIVED', name='cardstatus'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_batch_id'), 'cards', ['batch_id'], unique=False)
    op.create_index(op.f('ix_cards_owner_id'), 'cards', ['owner_id'], unique=False)
    op.create_table('decks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decks_owner_id'), 'decks', ['owner_id'], unique=False)
    op.create_table('ingest_inputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('URL', 'FILE', 'PASTED_TEXT', name='ingestkind'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', name='ingeststatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_inputs_user_id'), 'ingest_inputs', ['user_id'], unique=False)
    op.create_table('oauth_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_provider_uid')
    )
    op.create_index(op.f('ix_oauth_connections_user_id'), 'oauth_connections', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('RSS', 'HTML_LIST', 'GITHUB_REPO', 'YOUTUBE_CHANNEL', 'API_QUERY', 'NOTION_KB', 'X_SOCIAL', 'ARXIV_PAPER', 'WEB_RSS', 'CUSTOM', name='sourcetype'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('polling_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cursor_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ERROR', name='subscriptionstatus'), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('canonical_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('origin', sa.Enum('DIRECT', 'SUBSCRIPTION_ITEM', 'IMPORT', name='origintype'), nullable=False),
    sa.Column('ingest_input_id', sa.UUID(), nullable=True),
    sa.Column('origin_subscription_item_id', sa.UUID(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('doc_type', sa.Enum('PAPER', 'ARTICLE', 'VIDEO', 'AUDIO', 'PDF', 'REPO_DOC', 'OTHER', name='doctype'), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingest_input_id'], ['ingest_inputs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['origin_subscription_item_id'], ['subscription_items.id'], name='fk_canon_sub_item', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_documents_user_id'), 'canonical_documents', ['user_id'], unique=False)
    op.create_index('uq_canonical_user_url', 'canonical_documents', ['user_id', 'canonical_url'], unique=True, postgresql_where=sa.text('canonical_url IS NOT NULL'))
    op.create_table('card_decks',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'deck_id')
    )
    op.create_table('deck_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'deck_id')
    )
    op.create_table('review_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('state_before', sa.Enum('NEW', 'LEARNING', 'REVIEW', 'RELEARNING', name='fsrsstate'), nullable=False),
    sa.Column('state_after', sa.Enum('NEW', 'LEARNING', 'REVIEW', 'RELEARNING', name='fsrsstate'), nullable=False),
    sa.Column('scheduled_days', sa.Float(), nullable=False),
    sa.Column('elapsed_days', sa.Float(), nullable=False),
    sa.Column('review_duration_ms', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_logs_card_id'), 'review_logs', ['card_id'], unique=False)
    op.create_index(op.f('ix_review_logs_user_id'), 'review_logs', ['user_id'], unique=False)
    op.create_table('study_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('elapsed_days', sa.Float(), nullable=False),
    sa.Column('scheduled_days', sa.Float(), nullable=False),
    sa.Column('retrievability', sa.Float(), nullable=False),
    sa.Column('state', sa.Enum('NEW', 'LEARNING', 'REVIEW', 'RELEARNING', name='fsrsstate'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', name='uq_study_progress')
    )
    op.create_index('idx_study_queue', 'study_progress', ['user_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_study_progress_due_date'), 'study_progress', ['due_date'], unique=False)
    op.create_table('document_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_document_id', sa.UUID(), nullable=False),
    sa.Column('revision_kind', sa.Enum('SNAPSHOT', 'DIFF', name='revisionkind'), nullable=False),
    sa.Column('fetch_url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('extractor_key', sa.String(length=50), nullable=True),
    sa.Column('extractor_version', sa.String(length=20), nullable=True),
    sa.Column('extraction_status', sa.Enum('SUCCESS', 'FAILED', 'PARTIAL', name='extractionstatus'), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extracted_struct', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['canonical_document_id'], ['canonical_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_document_id', 'fingerprint', name='uq_rev_fp')
    )
    op.create_index('idx_rev_fetched', 'document_revisions', ['canonical_document_id', 'fetched_at'], unique=False)
    op.create_index(op.f('ix_document_revisions_canonical_document_id'), 'document_revisions', ['canonical_document_id'], unique=False)
    op.create_table('external_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('canonical_document_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_document_id'], ['canonical_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'external_id', name='uq_ext_mapping')
    )
    op.create_table('subscription_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('external_key', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('canonical_document_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_document_id'], ['canonical_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'external_key', name='uq_sub_item_key')
    )
    op.create_index(op.f('ix_subscription_items_subscription_id'), 'subscription_items', ['subscription_id'], unique=False)
    op.create_table('document_spans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('span_type', sa.Enum('PARAGRAPH', 'HEADING', 'CODE_BLOCK', 'TIMESTAMP_RANGE', 'OTHER', name='spantype'), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('(start_ms IS NULL OR end_ms IS NULL OR start_ms <= end_ms)', name='ck_span_ms_order'),
    sa.CheckConstraint('(start_offset IS NULL OR end_offset IS NULL OR start_offset <= end_offset)', name='ck_span_offsets_order'),
    sa.ForeignKeyConstraint(['revision_id'], ['document_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'ordinal', name='uq_span_rev_ord')
    )
    op.create_index('idx_span_rev_ord', 'document_spans', ['revision_id', 'ordinal'], unique=False)
    op.create_index(op.f('ix_document_spans_revision_id'), 'document_spans', ['revision_id'], unique=False)
    op.create_table('lens_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lens_id', sa.UUID(), nullable=True),
    sa.Column('lens_key', sa.String(length=100), nullable=False),
    sa.Column('input_revision_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='lensstatus'), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['input_revision_id'], ['document_revisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lens_id'], ['lenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lens_runs_input_revision_id'), 'lens_runs', ['input_revision_id'], unique=False)
    op.create_index(op.f('ix_lens_runs_lens_id'), 'lens_runs', ['lens_id'], unique=False)
    op.create_index(op.f('ix_lens_runs_user_id'), 'lens_runs', ['user_id'], unique=False)
    op.create_index('uq_lens_run_idempotency', 'lens_runs', ['user_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('card_evidences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['document_revisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['span_id'], ['document_spans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_evidences_card_id'), 'card_evidences', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_evidences_revision_id'), 'card_evidences', ['revision_id'], unique=False)
    op.create_table('card_generations',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('lens_run_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lens_run_id'], ['lens_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'lens_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_generations')
    op.drop_index(op.f('ix_card_evidences_revision_id'), table_name='card_evidences')
    op.drop_index(op.f('ix_card_evidences_card_id'), table_name='card_evidences')
    op.drop_table('card_evidences')
    op.drop_index('uq_lens_run_idempotency', table_name='lens_runs', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index(op.f('ix_lens_runs_user_id'), table_name='lens_runs')
    op.drop_index(op.f('ix_lens_runs_lens_id'), table_name='lens_runs')
    op.drop_index(op.f('ix_lens_runs_input_revision_id'), table_name='lens_runs')
    op.drop_table('lens_runs')
    op.drop_index(op.f('ix_document_spans_revision_id'), table_name='document_spans')
    op.drop_index('idx_span_rev_ord', table_name='document_spans')
    op.drop_table('document_spans')
    op.drop_index(op.f('ix_subscription_items_subscription_id'), table_name='subscription_items')
    op.drop_table('subscription_items')
    op.drop_table('external_mappings')
    op.drop_index(op.f('ix_document_revisions_canonical_document_id'), table_name='document_revisions')
    op.drop_index('idx_rev_fetched', table_name='document_revisions')
    op.drop_table('document_revisions')
    op.drop_index(op.f('ix_study_progress_due_date'), table_name='study_progress')
    op.drop_index('idx_study_queue', table_name='study_progress')
    op.drop_table('study_progress')
    op.drop_index(op.f('ix_review_logs_user_id'), table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_card_id'), table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_table('deck_subscriptions')
    op.drop_table('card_decks')
    op.drop_index('uq_canonical_user_url', table_name='canonical_documents', postgresql_where=sa.text('canonical_url IS NOT NULL'))
    op.drop_index(op.f('ix_canonical_documents_user_id'), table_name='canonical_documents')
    op.drop_table('canonical_documents')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_oauth_connections_user_id'), table_name='oauth_connections')
    op.drop_table('oauth_connections')
    op.drop_index(op.f('ix_ingest_inputs_user_id'), table_name='ingest_inputs')
    op.drop_table('ingest_inputs')
    op.drop_index(op.f('ix_decks_owner_id'), table_name='decks')
    op.drop_table('decks')
    op.drop_index(op.f('ix_cards_owner_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_batch_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('lenses')
    # ### end Alembic commands ###
