"""refactor card deck m2m

Revision ID: 4c365dfc9ac8
Revises: 5adce4e4881d
Create Date: 2026-01-28 10:38:50.959483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c365dfc9ac8'
down_revision: Union[str, None] = '5adce4e4881d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_decks',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'deck_id')
    )
    
    # 1. Add owner_id as NULLABLE first
    op.add_column('cards', sa.Column('owner_id', sa.UUID(), nullable=True))
    
    # 2. Backfill owner_id from decks
    op.execute("""
        UPDATE cards 
        SET owner_id = decks.owner_id 
        FROM decks 
        WHERE cards.deck_id = decks.id
    """)
    
    # 3. Populate card_decks mapping
    op.execute("""
        INSERT INTO card_decks (card_id, deck_id) 
        SELECT id, deck_id FROM cards WHERE deck_id IS NOT NULL
    """)

    # 4. Handle any remaining NULL owner_ids (if any) -> Delete them or default? 
    # For safe dev migration, we delete orphans
    op.execute("DELETE FROM cards WHERE owner_id IS NULL")

    # 5. Make owner_id NOT NULL
    op.alter_column('cards', 'owner_id', nullable=False)
    
    op.drop_index(op.f('ix_cards_deck_id'), table_name='cards')
    op.create_index(op.f('ix_cards_owner_id'), 'cards', ['owner_id'], unique=False)
    op.drop_constraint('cards_deck_id_fkey', 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cards', 'deck_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('deck_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key(op.f('cards_deck_id_fkey'), 'cards', 'decks', ['deck_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_cards_owner_id'), table_name='cards')
    op.create_index(op.f('ix_cards_deck_id'), 'cards', ['deck_id'], unique=False)
    op.drop_column('cards', 'owner_id')
    op.drop_table('card_decks')
    # ### end Alembic commands ###
