"""add_rich_data_to_source_material

Revision ID: 5adce4e4881d
Revises: db60202ea867
Create Date: 2026-01-27 18:19:07.712305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5adce4e4881d'
down_revision: Union[str, None] = 'db60202ea867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_materials', sa.Column('rich_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_materials', 'rich_data')
    # ### end Alembic commands ###
