"""add_batch_id_and_batch_index_to_cards

Revision ID: d9b662274e1f
Revises: 4c365dfc9ac8
Create Date: 2026-01-28 16:05:15.592521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b662274e1f'
down_revision: Union[str, None] = '4c365dfc9ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.add_column('cards', sa.Column('batch_index', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cards_batch_id'), 'cards', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_batch_id'), table_name='cards')
    op.drop_column('cards', 'batch_index')
    op.drop_column('cards', 'batch_id')
    # ### end Alembic commands ###
