"""Add full FSRS state to ReviewLog

Revision ID: dc9ebe2495ec
Revises: add_step_key_to_source_logs
Create Date: 2026-02-22 11:25:53.097673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc9ebe2495ec'
down_revision: Union[str, None] = 'add_step_key_to_source_logs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(table_name: str, column_name: str) -> bool:
    """Check if a column exists in the given table."""
    bind = op.get_bind()
    result = bind.execute(sa.text(
        "SELECT 1 FROM information_schema.columns "
        "WHERE table_name = :table AND column_name = :col"
    ), {"table": table_name, "col": column_name})
    return result.fetchone() is not None


def _index_exists(index_name: str) -> bool:
    """Check if an index exists."""
    bind = op.get_bind()
    result = bind.execute(sa.text(
        "SELECT 1 FROM pg_indexes WHERE indexname = :idx"
    ), {"idx": index_name})
    return result.fetchone() is not None


def _constraint_exists(constraint_name: str, table_name: str) -> bool:
    """Check if a constraint exists."""
    bind = op.get_bind()
    result = bind.execute(sa.text(
        "SELECT 1 FROM information_schema.table_constraints "
        "WHERE constraint_name = :con AND table_name = :table"
    ), {"con": constraint_name, "table": table_name})
    return result.fetchone() is not None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Made fully idempotent: check column/index/constraint existence before every operation

    if _column_exists('cards', 'type'):
        op.alter_column('cards', 'type',
                   existing_type=sa.VARCHAR(length=20),
                   type_=sa.String(length=30),
                   existing_nullable=False)
    if _column_exists('cards', 'updated_at'):
        op.drop_column('cards', 'updated_at')

    if _column_exists('deck_subscriptions', 'created_at'):
        op.alter_column('deck_subscriptions', 'created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=False,
                   existing_server_default=sa.text('now()'))
    if _column_exists('deck_subscriptions', 'role'):
        op.drop_column('deck_subscriptions', 'role')
    if _column_exists('deck_subscriptions', 'joined_at'):
        op.drop_column('deck_subscriptions', 'joined_at')

    if _column_exists('decks', 'title'):
        op.alter_column('decks', 'title',
                   existing_type=sa.VARCHAR(length=255),
                   type_=sa.String(length=100),
                   existing_nullable=False)
    if _column_exists('decks', 'updated_at'):
        op.drop_column('decks', 'updated_at')

    if _index_exists('ix_pipeline_templates_is_system'):
        op.drop_index(op.f('ix_pipeline_templates_is_system'), table_name='pipeline_templates')

    if not _column_exists('review_logs', 'stability_after'):
        op.add_column('review_logs', sa.Column('stability_after', sa.Float(), nullable=True))
    if not _column_exists('review_logs', 'difficulty_after'):
        op.add_column('review_logs', sa.Column('difficulty_after', sa.Float(), nullable=True))
    if _column_exists('review_logs', 'state_before'):
        op.alter_column('review_logs', 'state_before',
                   existing_type=postgresql.ENUM('new', 'learning', 'review', 'relearning', name='fsrsstate'),
                   nullable=True)
    if _column_exists('review_logs', 'state_after'):
        op.alter_column('review_logs', 'state_after',
                   existing_type=postgresql.ENUM('new', 'learning', 'review', 'relearning', name='fsrsstate'),
                   nullable=True)
    if _column_exists('review_logs', 'review_duration_ms'):
        op.alter_column('review_logs', 'review_duration_ms',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    if _column_exists('review_logs', 'grade'):
        op.drop_column('review_logs', 'grade')
    if _column_exists('review_logs', 'elapsed_days'):
        op.drop_column('review_logs', 'elapsed_days')
    if _column_exists('review_logs', 'scheduled_days'):
        op.drop_column('review_logs', 'scheduled_days')

    if _index_exists('ix_study_progress_due_date'):
        op.drop_index(op.f('ix_study_progress_due_date'), table_name='study_progress')
    if _constraint_exists('uq_study_progress', 'study_progress'):
        op.drop_constraint(op.f('uq_study_progress'), 'study_progress', type_='unique')
    if not _constraint_exists('uq_study_user_card', 'study_progress'):
        op.create_unique_constraint('uq_study_user_card', 'study_progress', ['user_id', 'card_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_study_user_card', 'study_progress', type_='unique')
    op.create_unique_constraint(op.f('uq_study_progress'), 'study_progress', ['user_id', 'card_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_study_progress_due_date'), 'study_progress', ['due_date'], unique=False)
    op.add_column('review_logs', sa.Column('scheduled_days', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('review_logs', sa.Column('elapsed_days', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('review_logs', sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('review_logs', 'review_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('review_logs', 'state_after',
               existing_type=postgresql.ENUM('new', 'learning', 'review', 'relearning', name='fsrsstate'),
               nullable=False)
    op.alter_column('review_logs', 'state_before',
               existing_type=postgresql.ENUM('new', 'learning', 'review', 'relearning', name='fsrsstate'),
               nullable=False)
    op.drop_column('review_logs', 'difficulty_after')
    op.drop_column('review_logs', 'stability_after')
    op.create_index(op.f('ix_pipeline_templates_is_system'), 'pipeline_templates', ['is_system'], unique=False)
    op.add_column('decks', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('decks', 'title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('deck_subscriptions', sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('deck_subscriptions', sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('deck_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('cards', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('cards', 'type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
