"use client"

import { DetailPanel } from "@/components/layout/DetailPanel"
import { Button } from "@/components/ui/button"
import { X, Check } from "lucide-react"

interface SourceCompareDrawerProps {
    isOpen: boolean
    onClose: () => void
    item: any // Type this properly in a real app
}

export function SourceCompareDrawer({ isOpen, onClose, item }: SourceCompareDrawerProps) {
    if (!item) return null

    return (
        <DetailPanel
            isOpen={isOpen}
            onClose={onClose}
            className="w-[800px] border-l shadow-2xl flex flex-col p-0 bg-background"
        >
            {/* Header */}
            <div className="flex items-center justify-between px-6 py-4 border-b bg-card">
                <div>
                    <h2 className="text-lg font-semibold">Review Generation</h2>
                    <p className="text-sm text-muted-foreground">Verify AI accuracy against the source</p>
                </div>
                <div className="flex items-center gap-2">
                    <Button variant="outline" size="sm" onClick={onClose}>
                        Cancel
                    </Button>
                    <Button size="sm" className="gap-2">
                        <Check className="h-4 w-4" />
                        Approve & Save
                    </Button>
                </div>
            </div>

            <div className="flex-1 flex overflow-hidden">
                {/* Left: Source */}
                <div className="flex-1 overflow-y-auto p-6 border-r pr-6 bg-muted/10">
                    <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wider mb-4 sticky top-0 bg-background/95 backdrop-blur py-2">Source Text</h3>
                    <div className="prose dark:prose-invert text-sm max-w-none">
                        <p className="whitespace-pre-wrap leading-relaxed opacity-90">
                            {item.fullText || "Source text content not available."}
                            {/* Mock long text */}
                            {Array(5).fill(null).map((_, i) => (
                                <span key={i} className="block mt-4">
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                </span>
                            ))}
                        </p>
                    </div>
                </div>

                {/* Right: AI Output */}
                <div className="flex-1 overflow-y-auto p-6 pl-6 bg-background">
                    <h3 className="text-sm font-medium text-primary uppercase tracking-wider mb-4 sticky top-0 bg-background/95 backdrop-blur py-2">AI Generated Assets</h3>

                    <div className="space-y-6">
                        {/* Flashcards */}
                        <div className="space-y-3">
                            <h4 className="font-medium flex items-center gap-2">
                                Generated Flashcards
                                <span className="text-xs font-normal text-muted-foreground bg-muted px-2 py-0.5 rounded-full">3</span>
                            </h4>
                            {[1, 2, 3].map((i) => (
                                <div key={i} className="border rounded-lg p-4 text-sm bg-card hover:border-primary/50 transition-colors group relative">
                                    <div className="font-medium mb-2 text-primary/80">Q: What is the core concept here?</div>
                                    <div className="text-muted-foreground">A: This represents the answer generated by the AI model based on the source text.</div>
                                    <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100">
                                        <Button variant="ghost" size="icon" className="h-6 w-6"><X className="h-3 w-3" /></Button>
                                    </div>
                                </div>
                            ))}
                        </div>

                        {/* Quiz */}
                        <div className="space-y-3">
                            <h4 className="font-medium flex items-center gap-2">
                                Quiz Question
                                <span className="text-xs font-normal text-muted-foreground bg-muted px-2 py-0.5 rounded-full">1</span>
                            </h4>
                            <div className="border rounded-lg p-4 text-sm bg-card">
                                <div className="font-medium mb-3">Which of the following best describes the author's intent?</div>
                                <div className="space-y-2">
                                    {['To inform', 'To persuade', 'To entertain'].map(opt => (
                                        <div key={opt} className="flex items-center gap-2 p-2 rounded hover:bg-muted cursor-pointer">
                                            <div className="h-4 w-4 rounded-full border" />
                                            <span>{opt}</span>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </DetailPanel>
    )
}
